# Importy 

In [18]:
import numpy as np
import pandas as pd
import itertools

# MCKP Class with functions

In [19]:
class MCKP:
    def __init__(self,class_number,item_numbers,max_combinations):
        self.class_number = class_number
        self.item_numbers = item_numbers
        self.max_combinations = max_combinations
        self.classes = []
        self.combinations=[]
        self.sorted_viz_list =[]
        self.final_sum = 0
        self.class_n = [i+1 for i in range(5)]
        self.sorted_viz_list = [ ]
        self.final_sum = 0
        self.res_ls = []
        self.items_list = []
        self.solution, self.it_list, self.items,self.cominations = self.get_bags(self.class_number,self.item_numbers,self.max_combinations)

    def get_class_numbers(self,class_number,item_numbers):
        for _ in range(class_number):
            item_dic = { }
            for i in range(item_numbers):
                item_dic.update({i+1:[np.random.randint(1,50),np.random.randint(1,50)]})
            self.classes.append(item_dic)
        return self.classes

    def get_comb_mat(self,class_number,item_numbers):
        for _ in range(class_number):
            step = [ ]
            for i in range(item_numbers):
                step.append(i+1)
            self.combinations.append(step)
        return np.array(list(itertools.product(*self.combinations)))
    
    def get_viz(self):
        for i in range(len(self.items)):
            sorted_ls = [ ]
            sorted_ls.append(self.class_n[i])
            sorted_ls.append(self.items[i])
            sorted_ls.append(self.it_list[i][1])
            sorted_ls.append(self.it_list[i][0])
            self.final_sum += self.it_list[i][1]
            self.sorted_viz_list.append(sorted_ls)
        self.sorted_viz_list.append(['','Sum',self.final_sum,self.solution])
        DF = pd.DataFrame(self.sorted_viz_list)
        DF.columns = ['Class','Id','Capacity','Price']
        return DF    

    def get_bags(self,class_number,item_numbers,max_combinations):
        it_classes = self.get_class_numbers(class_number,item_numbers)
        cb_arr = self.get_comb_mat(class_number,item_numbers)
        
        for i in cb_arr:
            row_val,res,max = 0,0,0
            for col_val in i:
                res += it_classes[row_val][col_val][0]
                max += it_classes[row_val][col_val][1]
                row_val += 1
            if max > max_combinations:
                self.res_ls.append(class_number*50)
            else:
                self.res_ls.append(res)
        min_res = min(self.res_ls)
        inedx_min = np.argmin(self.res_ls)
        items = cb_arr[inedx_min]
        for i in range(class_number):
            self.items_list.append(it_classes[i][items[i]])
        return min_res, self.items_list, items, cb_arr

# Calling our class

In [20]:
mckp = MCKP(5,3,100)
print(mckp.cominations)
mckp.get_viz()

[[1 1 1 1 1]
 [1 1 1 1 2]
 [1 1 1 1 3]
 ...
 [3 3 3 3 1]
 [3 3 3 3 2]
 [3 3 3 3 3]]


Class   Id  Capacity  Price
0     1    1        12     42
1     2    1        12     25
2     3    2        11      9
3     4    2        14     11
4     5    3        50     18
5        Sum        99    105